version: "3"
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  cache:
    image: "redis"
    ports:
      - "6379:6379"
    command: >
      --requirepass ${CACHE_PASSWORD}
volumes:
  data:
